services:
  - type: web
    name: partner-app-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DATABASE_URL
        fromDatabase:
          name: partner-app-db
          property: connectionString
